version: "2"
services:
  api:
    build: .
    ports:
      - 5000:5000

  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ehealth
    ports:
      - 4030:3036

    # volumes:
    #   - db-config:/etc/mysql
    #   - db-data:/var/lib/mysql
    #   - ./db/backup/files/:/data_backup/data
